custom:
  enable_rule_generator: false
  overwrite_original_rules: false

  proxy_groups:
  - {import: https://raw.githubusercontent.com/NZESupB/SubConver-Clash-Profile/master/groups.txt}
# - {import: snippets/groups_forcerule.txt}

  rulesets:
	- {import: https://raw.githubusercontent.com/NZESupB/SubConver-Clash-Profile/master/rulesets.txt}
  - {ruleset: "clash-classic:https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Telegram/Telegram.yaml", group: "ğŸ“² ç”µæŠ¥ä¿¡æ¯"}
  - {ruleset: "clash-classic:https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml", group: "ğŸŒ å›½å¤–åª’ä½“"}
  - {ruleset: "clash-classic:https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml", group: "ğŸŒ å›½å†…åª’ä½“"}
  - {ruleset: "clash-classic:https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingCN.yaml", group: "ğŸŒ å›½å†…åª’ä½“"}
  - {ruleset: "clash-classic:https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Advertising.yaml", group: "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"}
  - {ruleset: "clash-classic:https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Hijacking.yaml", group: "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"}
  - {ruleset: "clash-classic:https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml", group: "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"}
  # - {ruleset: "clash-ipcidr:https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml", group: "ğŸ¯ å…¨çƒç›´è¿"}
  - {ruleset: "clash-classic:https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml", group: "ğŸ¯ å…¨çƒç›´è¿"}
  - {rule: "GEOIP,CN", group: "ğŸ¯ å…¨çƒç›´è¿"}
  - {rule: "FINAL", group: "ğŸŸ æ¼ç½‘ä¹‹é±¼"}
#  - {import: snippets/ruleset_remote.txt}

#  clash_rule_base: base/all_base.tpl
#  surge_rule_base: base/surge.conf
#  surfboard_rule_base: base/surfboard.conf
#  mellow_rule_base: base/mellow.conf
#  quan_rule_base: base/quan.conf
#  quanx_rule_base: base/quanx.conf

   rename_node:
	 - {import: https://raw.githubusercontent.com/NZESupB/SubConver-Clash-Profile/master/rename_node.txt}
#  - {import: snippet/rename.txt}

  add_emoji: true
  remove_old_emoji: true
  emojis:
  - {import: https://raw.githubusercontent.com/NZESupB/SubConver-Clash-Profile/master/emoji.txt}
#  - {import: snippets/emoji.txt}

#  include_remarks: []
   exclude_remarks: ["(åˆ°æœŸ|æµé‡|æ—¶é—´|å®˜ç½‘|äº§å“|å¹³å°|åæ‰|è¯•ç”¨|IPV6|ipv6|æ¼æ´|ç”¨æˆ·|ç»­è´¹)"]
#  template_args:
#  - {key: clash.dns.port, value: 5353}
